targets:
  $default:
    builders:
      textstyle_generator|textstyle_builder:
        options:
          font_path: assets/fonts/
          min: 8
          max: 24
          default_palette: Palette().black()
          output_dir: lib/generated_assets/
          class_name: T
